<?php

namespace AppBundle\Repository;

/**
 * BenefactorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BenefactorRepository extends \Doctrine\ORM\EntityRepository
{
}
