AppBundle\Entity\Benefactor:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\BenefactorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
      campaign:
        targetEntity: AppBundle\Entity\Campaign
        inversedBy: benefactors
    oneToOne:
      project:
        targetEntity: AppBundle\Entity\Project
        inversedBy: benefactor
      organization:
        targetEntity: AppBundle\Entity\Organization
        inversedBy: benefactor

    lifecycleCallbacks: {  }
