AppBundle\Entity\Campaign:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CampaignRepository
    id:
      id:
        type: integer
        id: true
        generator:
          strategy: AUTO
    manyToMany:
      staff:
        targetEntity: AppBundle\Entity\Staff
        mappedBy: campaigns
    oneToMany:
      benefactors:
        targetEntity: AppBundle\Entity\Benefactor
        mappedBy: campaign
      donations:
        targetEntity: AppBundle\Entity\Donation
        mappedBy: campaign
    lifecycleCallbacks: {  }
