AppBundle\Entity\Campaign:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CampaignRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
      campaign:
        targetEntity: AppBundle\Entity\Campaign
      donation:
        targetEntity: AppBundle\Entity\Donation
    manyToMany:
      staff:
        targetEntity: AppBundle\Entity\Staff
    lifecycleCallbacks: {  }
