AppBundle\Entity\Donation:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\DonationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        donor:
            targetEntity: AppBundle\Entity\Donor
            inversedBy: donations
        campaign:
            targetEntity: AppBundle\Entity\Campaign
            inversedBy: donations
        organization:
            targetEntity: AppBundle\Entity\Organization
            inversedBy: donations
    oneToOne:
        movement:
            targetEntity: AppBundle\Entity\Movement
            mappedBy: donation
    lifecycleCallbacks: {  }
