AppBundle\Entity\Donor:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\DonorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    oneToMany:
      donations:
        targetEntity: AppBundle\Entity\Donation
        mappedBy: donor
    oneToOne:
      profile:
        targetEntity: AppBundle\Entity\Profile
    lifecycleCallbacks: {  }
