AppBundle\Entity\Movement:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MovementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
      donation:
        targetEntity: AppBundle\Entity\Donation
        inversedBy: movement
    lifecycleCallbacks: {  }
