AppBundle\Entity\Organization:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\OrganizationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
      projects:
        targetEntity: AppBundle\Entity\Project
        mappedBy: organization
      donations:
        targetEntity: AppBundle\Entity\Donation
        mappedBy: organization
    oneToOne:
      benefactor:
        targetEntity: AppBundle\Entity\Benefactor
        mappedBy: organization
    lifecycleCallbacks: {  }
