AppBundle\Entity\Profile:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProfileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
