AppBundle\Entity\Project:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProjectRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
      organization:
        targetEntity: AppBundle\Entity\Organization
        inversedBy: projects
    manyToMany:
      staff:
        targetEntity: AppBundle\Entity\Staff
        mappedBy: projects
    oneToOne:
      benefactor:
        targetEntity: AppBundle\Entity\Benefactor
        mappedBy: project

    lifecycleCallbacks: {  }
