AppBundle\Entity\Staff:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\StaffRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToMany:
      projects:
        targetEntity: AppBundle\Entity\Project
        inversedBy: staff
      campaigns:
        targetEntity: AppBundle\Entity\Campaign
        inversedBy: staff
    manyToOne:
      profile:
        targetEntity: AppBundle\Entity\Profile
    lifecycleCallbacks: {  }
